# Generated by Django 3.1.4 on 2020-12-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='mdeai/default.png', upload_to='media'),
        ),
    ]
